### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by Oggerschummer** [shamzahasan88/HHCustomCorner#2]
Hi,
could you provide support for the Swift Package Manager ?
Would be great and an option to get rid of CocoaPod.

**Comment by shamzahasan88** [comment]
@Oggerschummer, I appreciate your valuable suggestion and my sincere apologies for the delay in response. I'm delighted to let you know that your idea has been put into action, and we now support Swift Package Manager for our library.

It's all set up and thoroughly tested! Thank you again for bringing this to our attention.
